In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)

n_records = 20000

data = pd.DataFrame({
    'user_id': np.random.randint(1000,1050,n_records),
    'amount': np.random.exponential(scale=45,size=n_records),
    'hours_since_last_tx': np.random.exponential(scale=18,size=n_records),
    'distance_from_home_miles': np.random.exponential(scale=8,size=n_records),
    'device_type': np.random.choice(
        ['Mobile','Desktop','Tablet'],
        n_records,
        p=[0.7,0.2,0.1]
    ),
    'is_fraud':0
})

data.head()

,user_id,amount,hours_since_last_tx,distance_from_home_miles,device_type,is_fraud
0,1038,27.314538,23.213075,6.665770,Mobile,0
1,1028,7.294124,18.406838,0.763408,Mobile,0
2,1014,26.880359,40.557329,3.914159,Desktop,0
3,1042,14.688532,13.198511,2.031422,Mobile,0
4,1007,129.040650,13.591342,1.060737,Mobile,0

In [3]:
fraud_indices = np.random.choice(
    n_records,
    size=200,
    replace=False
)

data.loc[fraud_indices,'amount'] = np.random.uniform(
    800,
    4500,
    size=200
)

data.loc[fraud_indices,'hours_since_last_tx'] = np.random.uniform(
    0.01,
    0.2,
    size=200
)

data.loc[fraud_indices,'distance_from_home_miles'] = np.random.uniform(
    300,
    4000,
    size=200
)

data.loc[fraud_indices,'device_type'] = 'Unknown'

data.loc[fraud_indices,'is_fraud'] = 1

In [4]:
data['is_fraud'].value_counts()

is_fraud
0    19800
1      200
Name: count, dtype: int64